// hotelcompanion_license.example.js
// ─────────────────────────────────────────────────────────────────────────────
// Example / reference license file for the Night Receptionist Companion Suite.
// © 2026 Whizzsfe Web Services — whizzsfe@gmail.com
//
// ─────────────────────────────────────────────────────────────────────────────
// HOW LICENSING WORKS
// ─────────────────────────────────────────────────────────────────────────────
//
// 1. Whizzsfe Web Services generates a signed license file for your property
//    using a private RSA-PSS key that never leaves Whizzsfe.
//
// 2. The signed file is named  hotelcompanion_license.js  and placed in the
//    same folder as  hotelcompanion_suite.html  (next to the executable on
//    Windows installs, or in the OneDrive sync folder for browser installs).
//
// 3. Every time the app loads it verifies the license cryptographically using
//    the embedded public key.  Any modification to any field — including the
//    dates — invalidates the signature and blocks the app.
//
// 4. License renewal: contact  whizzsfe@gmail.com  before your expiry date.
//    You will receive a new  hotelcompanion_license.js  to replace the old one.
//
// ─────────────────────────────────────────────────────────────────────────────
// FIELD REFERENCE
// ─────────────────────────────────────────────────────────────────────────────
//
//   version      — always 1. Used for forward-compatibility checks.
//   propertyName — the hotel / property name shown in the app ("Licensed to").
//   licenseeName — the legal entity that purchased the license.
//   issuedAt     — date the license was generated (YYYY-MM-DD). Do not change.
//   expiresAt    — date the license expires (YYYY-MM-DD). Do not change.
//   signature    — RSA-PSS SHA-256 signature over "propertyName|licenseeName|
//                  issuedAt|expiresAt" (base64). Generated by Whizzsfe.
//
// ─────────────────────────────────────────────────────────────────────────────
// THIS IS AN EXAMPLE FILE — the signature below is NOT valid.
// Do not rename this file to hotelcompanion_license.js; it will fail
// verification. Only use a file generated by Whizzsfe Web Services.
// ─────────────────────────────────────────────────────────────────────────────
window.HOTELCOMPANION_LICENSE = {
  version:      1,
  propertyName: 'The Grand Hotel',
  licenseeName: 'Grand Hotel Group Ltd',
  issuedAt:     '2026-05-09',
  expiresAt:    '2027-05-09',
  signature:    'EXAMPLE_SIGNATURE_NOT_VALID__contact_whizzsfe@gmail.com_for_a_real_license'
};
