#!/usr/bin/env node
'use strict';
// ─────────────────────────────────────────────────────────────────────────────
// generate-license.js  — Night Receptionist Companion  (vendor-only CLI tool)
// © 2026 Whizzsfe Web Services
//
// MODES
//   --keygen
//       Generate a new RSA-PSS-2048 key pair.
//       Writes  scripts/public-key.pem  and  scripts/private-key.pem
//       (both are .gitignored — never commit them).
//       Also prints the base64 SPKI DER string to embed in the HTML files.
//
//   --property "Hotel Name"  --licensee "Company Ltd"  --expires YYYY-MM-DD
//       Generate a signed hotelcompanion_license.js for a client.
//       Optional: --out <path>   (default: ./hotelcompanion_license.js)
//                 --key <path>   (default: scripts/private-key.pem)
//
// SIGNED PAYLOAD (pipe-delimited, UTF-8)
//   "propertyName|licenseeName|issuedAt|expiresAt"
//   Changing ANY field invalidates the signature.
// ─────────────────────────────────────────────────────────────────────────────

const crypto = require('node:crypto');
const fs     = require('node:fs');
const path   = require('node:path');

const SCRIPTS_DIR = __dirname;

// ── CLI arg parser ────────────────────────────────────────────────────────────
const args = {};
const argv = process.argv.slice(2);
for (let i = 0; i < argv.length; i++) {
  const a = argv[i];
  if (a.startsWith('--')) {
    const key = a.slice(2);
    const next = argv[i + 1];
    args[key] = (next && !next.startsWith('--')) ? (i++, next) : true;
  }
}

// ── --keygen mode ─────────────────────────────────────────────────────────────
if (args.keygen) {
  console.log('\nGenerating RSA-PSS 2048-bit key pair…\n');

  const { publicKey, privateKey } = crypto.generateKeyPairSync('rsa', {
    modulusLength: 2048,
    publicKeyEncoding:  { type: 'spki',  format: 'pem' },
    privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
  });

  // Write both keys to scripts/ (gitignored).
  const pubPath  = path.join(SCRIPTS_DIR, 'public-key.pem');
  const privPath = path.join(SCRIPTS_DIR, 'private-key.pem');
  fs.writeFileSync(pubPath,  publicKey,  'utf8');
  fs.writeFileSync(privPath, privateKey, 'utf8');

  // Derive the base64 SPKI DER — this is what gets embedded in the HTML.
  const pubKeyObj = crypto.createPublicKey(publicKey);
  const spkiDer   = pubKeyObj.export({ type: 'spki', format: 'der' });
  const spkiB64   = spkiDer.toString('base64');

  console.log('✓ Public key written to:  ' + pubPath);
  console.log('✓ Private key written to: ' + privPath);
  console.log('\n⚠  KEEP PRIVATE KEY SECURE. Do not commit it. It is already .gitignored.\n');

  console.log('═══════════════════════════════════════════════════════════════');
  console.log('PASTE THIS VALUE as  LICENSE_PUBLIC_KEY_B64  in both HTML files');
  console.log('═══════════════════════════════════════════════════════════════');
  console.log(spkiB64);
  console.log('═══════════════════════════════════════════════════════════════\n');

  process.exit(0);
}

// ── --property / --licensee / --expires mode ──────────────────────────────────
if (args.property && args.licensee && args.expires) {
  // Validate expiry date format
  if (!/^\d{4}-\d{2}-\d{2}$/.test(args.expires)) {
    console.error('Error: --expires must be YYYY-MM-DD');
    process.exit(1);
  }

  // Load private key
  const keyPath = args.key || path.join(SCRIPTS_DIR, 'private-key.pem');
  if (!fs.existsSync(keyPath)) {
    console.error(`Error: Private key not found at ${keyPath}`);
    console.error('Run  node scripts/generate-license.js --keygen  first.');
    process.exit(1);
  }
  const privateKeyPem = fs.readFileSync(keyPath, 'utf8');

  const issuedAt = new Date().toISOString().slice(0, 10); // YYYY-MM-DD

  // Build the signed payload — order is significant and must match the HTML verifier.
  const payload    = `${args.property}|${args.licensee}|${issuedAt}|${args.expires}`;
  const payloadBuf = Buffer.from(payload, 'utf8');

  // Sign with RSA-PSS SHA-256, salt length = digest size (32 bytes for SHA-256).
  const signature = crypto.sign('sha256', payloadBuf, {
    key:        privateKeyPem,
    padding:    crypto.constants.RSA_PKCS1_PSS_PADDING,
    saltLength: crypto.constants.RSA_PSS_SALTLEN_DIGEST, // 32 for SHA-256
  });
  const sigBase64 = signature.toString('base64');

  // Build the license file content.
  const licenseJs = `// hotelcompanion_license.js
// ─────────────────────────────────────────────────────────────────────────────
// Night Receptionist Companion Suite — License File
// Generated by Whizzsfe Web Services
//
// Property : ${args.property}
// Licensee : ${args.licensee}
// Issued   : ${issuedAt}
// Expires  : ${args.expires}
//
// ⚠  DO NOT MODIFY THIS FILE. It is cryptographically signed.
//    Any change to any value (including dates) will invalidate the license.
//    Contact whizzsfe@gmail.com for a replacement or renewal.
// ─────────────────────────────────────────────────────────────────────────────
window.HOTELCOMPANION_LICENSE = {
  version:      1,
  propertyName: ${JSON.stringify(args.property)},
  licenseeName: ${JSON.stringify(args.licensee)},
  issuedAt:     ${JSON.stringify(issuedAt)},
  expiresAt:    ${JSON.stringify(args.expires)},
  signature:    ${JSON.stringify(sigBase64)}
};
`;

  const outPath = args.out
    ? path.resolve(process.cwd(), args.out)
    : path.join(process.cwd(), 'hotelcompanion_license.js');

  fs.writeFileSync(outPath, licenseJs, 'utf8');

  console.log(`\n✓ License written to: ${outPath}`);
  console.log(`  Property : ${args.property}`);
  console.log(`  Licensee : ${args.licensee}`);
  console.log(`  Issued   : ${issuedAt}`);
  console.log(`  Expires  : ${args.expires}\n`);

  process.exit(0);
}

// ── Usage ─────────────────────────────────────────────────────────────────────
console.log(`
Night Receptionist Companion — License Generator
© 2026 Whizzsfe Web Services

USAGE

  node scripts/generate-license.js --keygen
    Generate a new RSA-PSS 2048-bit key pair.
    Writes scripts/public-key.pem and scripts/private-key.pem (both gitignored).
    Prints the base64 SPKI DER public key to embed in the HTML files.
    Run this ONCE and store the private key securely.

  node scripts/generate-license.js \\
       --property  "Hotel Name" \\
       --licensee  "Company Ltd" \\
       --expires   YYYY-MM-DD \\
       [--out      path/to/hotelcompanion_license.js] \\
       [--key      path/to/private-key.pem]
    Generate a signed license file for a client property.
    Default output : hotelcompanion_license.js (current directory)
    Default key    : scripts/private-key.pem

EXAMPLES

  # First-time key generation:
  node scripts/generate-license.js --keygen

  # License for a property expiring 2027-05-09:
  node scripts/generate-license.js \\
       --property "The Grand Hotel" \\
       --licensee "Grand Hotel Group Ltd" \\
       --expires  2027-05-09 \\
       --out      ./hotelcompanion_license.js
`);
process.exit(1);
